# Generated by Django 4.2.7 on 2023-12-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('usd', 'Доллары')], max_length=10, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'валюта',
                'verbose_name_plural': 'валюты',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('stripe_product_id', models.CharField(editable=False, max_length=100, null=True, verbose_name='внешний идентификатор продукта')),
                ('stripe_price_id', models.CharField(editable=False, max_length=100, null=True, verbose_name='внешний идентификатор цены')),
                ('stripe_product_status', models.CharField(default='pending', editable=False, max_length=25, verbose_name='статус получения внешнего ID продукта')),
                ('stripe_price_status', models.CharField(default='pending', editable=False, max_length=25, verbose_name='статус получения внешнего ID цены')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.currency', verbose_name='валюта')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=20, unique=True, verbose_name='код налога')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('description', models.CharField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'налог',
                'verbose_name_plural': 'налоги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название заказа')),
                ('items', models.ManyToManyField(to='orders.item', verbose_name='товары в заказе')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tax', verbose_name='налог')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tax', verbose_name='налог'),
        ),
    ]
